apiVersion: v1
kind: Service
metadata:
  name: deis-workflow-manager
  labels:
    heritage: deis
    router.deis.cc/routable: "true"
  annotations:
    router.deis.cc/domains: deis-workflow-manager
spec:
  selector:
    app: deis-workflow-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
